TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.1
  backup_vel: 0.3

  acc_limit_th: 0.6
  acc_limit_x: 0.25
  acc_limit_y: 0

  holonomic_robot: false

  yaw_goal_tolerance: 6.28
  xy_goal_tolerance: 0.5
