obstacle_range: 2.5
raytrace_range: 3.0 
footprint: [[0.3048, 0.3048], [0.3048, -0.3048], [-0.6096, -0.3048], [-0.6096, 0.3048]]
inflation_radius: 1.2
cost_scaling_factor: 0.0000001

observation_sources: base_laser

base_laser: {sensor_frame: base_laser_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
#laser_scan_sensor: {sensor_frame: frame_name, data_type: LaserScan, topic: topic_name, marking: true, clearing: true}
#
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
